### PR TITLE
Api call to fetch userlist.

### PR DESCRIPTION
**Pull request by Puja151**
fetch user list from api - done
display in list - done

Working for click event to refetch list - inprogress

### CODE REVIEW

**Comment by Puja151** [comment]
System crashed, need to do setup again for android studio. I am working on same. Sorry for delay. I will update my progress for the same. Thank you

**Comment by nets-dev** [comment]
@Puja151 You can focus on using the original `API` interface in the template and try to understand its structure. Replacing what is given there is not the approach we want to go.

**Comment by Puja151** [comment]
> @Puja151 You can focus on using the original `API` interface in the template and try to understand its structure. Replacing what is given there is not the approach we want to go.

Ok, I will update my PR accordingly. Thank you

**Comment by Puja151** [comment]
> @Puja151 You can focus on using the original `API` interface in the template and try to understand its structure. Replacing what is given there is not the approach we want to go.

Hi, bellow method I have to use as it is or I can modify it to return retrofit instance? 
        // TODO: Instantiate an API object as follows to use within the app
/*
        fun create() : API {
            return RetrofitAPI(usersListURL = usersListURL)
        }
        
 */
Thank you in advance
@nets-dev

**Comment by nets-dev** [comment]
@Puja151 You have to use it as it is. Its ok to modify the arguments in the constructor but do not return a retrofit instance. Retrofit is a third party library and the API interface can flexibly be implemented using Retrofit, Ktor or any other library. 
The application should not have a direct dependency on the networking library thats used. I hope this clarifies your question. Feel free to reach out if you have anymore questions

**Comment by Puja151** [comment]
Closing the PR

**Pull request closed without merging**
